# Generated by Django 2.0.1 on 2018-11-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('birthplace', models.CharField(max_length=200)),
                ('death_day', models.DateField()),
                ('death_place', models.CharField(max_length=200)),
            ],
        ),
    ]
